FROM httpd:2.4

# Install powershell for Debian 9
RUN apt-get update && apt-get install -y curl gnupg apt-transport-https
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch main" > /etc/apt/sources.list.d/microsoft.list'
RUN apt-get update && apt-get install -y powershell

# Change to powershell, lol
SHELL ["pwsh", "-Command"]

RUN $Path = '/usr/local/apache2/htdocs';\
    # Create folder structure and html file
    New-Item -Path $Path/index.html -Force | out-Null;\
    # Get the function
    Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/khaffner/Consumer-Tools/master/Get-Alcohol.ps1'));\
    # Run the function and save the data
    $Data = Get-Alcohol | Where-Object AlcoholPercentage -GT 1;\
    # Create html File
    $Data | Sort-Object PricePerAlcohol | ConvertTo-Html | Set-Content $Path/index.html -Force;\
    # Create csv File
    $Data | ConvertTo-Csv -Delimiter ';' | Set-Content $Path/data.csv;\
    # Create json data
    $Data | Convertto-JSON | Set-Content $Path/data.json

# Build: docker build --no-cache -t alcohol .
# Run: docker run -dit -p 8080:80 alcohol